# Generated by Django 3.2.4 on 2021-06-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGeekapp', '0002_rename_author_sala_nombre_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='description',
            new_name='Mensaje',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='author',
            new_name='Nombre_sala',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='title',
        ),
    ]
