# Generated by Django 3.2.4 on 2021-06-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoGeekapp', '0004_rename_mensaje_comentario_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='title',
            new_name='mensaje',
        ),
    ]
